import { Exam } from '../../models/entity/Exam';
import { getSeedList } from '../../services/sqlServices/SeedService';

export const getExamSeedData = (seed_courses: any) => getSeedList<Exam>()({
    signup_exam: {
        courseId: null,
        description: null,
        moduleId: null,
        orderIndex: null,
        retakeLimit: null,
        subtitle: null,
        thumbnailUrl: null,
        title: '[signup exam]',
        type: 'signup',
        deletionDate: null
    },
    exam_8: {
        title: 'Első lépések témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 15,
        type: 'normal',
        deletionDate: null,
        retakeLimit: null,
        courseId: seed_courses.course_24.id,
        moduleId: 2
    },
    exam_9: {
        title: 'Ismerkedés a függvényekkel témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 25,
        type: 'normal',
        deletionDate: null,
        retakeLimit: null,
        courseId: seed_courses.course_24.id,
        moduleId: 2
    },
    exam_10: {
        title: 'OBS Studio témazáró',
        subtitle: 'Nézzük át még egyszer az alapokat',
        description: null,
        thumbnailUrl: null,
        orderIndex: 1,
        type: 'normal',
        deletionDate: null,
        retakeLimit: null,
        courseId: seed_courses.course_17.id,
        moduleId: 8
    },
    exam_15: {
        title: 'Leggyakoribb függvények és azok használata témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 15,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_27.id,
        moduleId: 38
    },
    exam_16: {
        title: 'Segítség az adatkezelésben témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 11,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_27.id,
        moduleId: 39
    },
    exam_17: {
        title: 'Formázás felsőfokon témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 12,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_27.id,
        moduleId: 41
    },
    exam_18: {
        title: 'Munka nagy mennyiségű adattal témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 17,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_27.id,
        moduleId: 42
    },
    exam_20: {
        title: 'Microsoft Excel Alapok kurzuszáró vizsga',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 118,
        type: 'final',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_27.id,
        moduleId: 44
    },
    exam_21: {
        title: 'Első lépések témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 18,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_28.id,
        moduleId: 45
    },
    exam_12: {
        title: 'Első lépések témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 14,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_27.id,
        moduleId: 35
    },
    exam_13: {
        title: 'Ismerkedés a függvényekkel témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 9,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_27.id,
        moduleId: 36
    },
    exam_14: {
        title: 'A formázás alapjai témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 16,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_27.id,
        moduleId: 37
    },
    exam_22: {
        title: 'Formázás - Hogyan készíthetünk letisztult dokumentumokat? témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 29,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_28.id,
        moduleId: 47
    },
    exam_23: {
        title: 'Gyorsabb munka a gyakorlatban témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 17,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_28.id,
        moduleId: 48
    },
    exam_24: {
        title: 'Szövegírás, elrendezés, ellenőrzés témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 18,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_28.id,
        moduleId: 50
    },
    exam_25: {
        title: 'Képek, vizuális eszközök használata témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 18,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_28.id,
        moduleId: 51
    },
    exam_26: {
        title: 'Microsoft Word Alapok kurzus záróvizsga',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 123,
        type: 'final',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_28.id,
        moduleId: 53
    },
    exam_27: {
        title: 'Első lépések témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 25,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_22.id,
        moduleId: 54
    },
    exam_28: {
        title: 'Szöveg és tartalom formázása témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 13,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_22.id,
        moduleId: 55
    },
    exam_29: {
        title: 'Képek, vizuális eszközök használata témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 19,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_22.id,
        moduleId: 56
    },
    exam_30: {
        title: 'Videók és hanganyagok használata a PowerPointon belül témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 5,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_22.id,
        moduleId: 57
    },
    exam_31: {
        title: 'Prezentáció rendszerezése, segítség az előadás során témazáró',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 12,
        type: 'normal',
        deletionDate: null,
        retakeLimit: 3,
        courseId: seed_courses.course_22.id,
        moduleId: 58
    },
    exam_32: {
        title: ' Microsoft PowerPoint Alapok kurzus záróvizsga',
        subtitle: '',
        description: null,
        thumbnailUrl: null,
        orderIndex: 4,
        type: 'final',
        deletionDate: null,
        retakeLimit: 1,
        courseId: seed_courses.course_22.id,
        moduleId: 60
    },
    pretest_exam_33: {
        courseId: seed_courses.course_24.id,
        title: 'Pretest exam course 1',
        subtitle: 'Pretest exam course 1 desc',
        description: '',
        orderIndex: 0,
        moduleId: null,
        type: 'pretest',
        retakeLimit: null,
        thumbnailUrl: null,
        deletionDate: null
    },
    pretest_exam_34: {
        courseId: seed_courses.course_29.id,
        title: 'Pretest exam course 10',
        subtitle: 'Pretest exam course 10 desc',
        description: '',
        orderIndex: 0,
        moduleId: null,
        type: 'pretest',
        retakeLimit: null,
        thumbnailUrl: null,
        deletionDate: null
    },
    pretest_exam_35: {
        courseId: seed_courses.course_23.id,
        title: 'Pretest exam course 23',
        subtitle: 'Pretest exam course 23 desc',
        description: '',
        orderIndex: 0,
        moduleId: null,
        type: 'pretest',
        retakeLimit: null,
        thumbnailUrl: null,
        deletionDate: null
    },
    pretest_exam_36: {
        courseId: seed_courses.course_24.id,
        title: 'Pretest exam course 24',
        subtitle: 'Pretest exam course 24 desc',
        description: '',
        orderIndex: 0,
        moduleId: null,
        type: 'pretest',
        retakeLimit: null,
        thumbnailUrl: null,
        deletionDate: null
    },
    pretest_exam_37: {
        courseId: seed_courses.course_26.id,
        title: 'Pretest exam course 26',
        subtitle: 'Pretest exam course 26 desc',
        description: '',
        orderIndex: 0,
        moduleId: null,
        type: 'pretest',
        retakeLimit: null,
        thumbnailUrl: null,
        deletionDate: null
    },
    pretest_exam_38: {
        courseId: seed_courses.course_25.id,
        title: 'Pretest exam course 25',
        subtitle: 'Pretest exam course 25 desc',
        description: '',
        orderIndex: 0,
        moduleId: null,
        type: 'pretest',
        retakeLimit: null,
        thumbnailUrl: null,
        deletionDate: null
    },
    pretest_exam_39: {
        courseId: seed_courses.course_28.id,
        title: 'Word',
        subtitle: 'Kezdés',
        description: '',
        orderIndex: 0,
        moduleId: null,
        type: 'pretest',
        retakeLimit: null,
        thumbnailUrl: null,
        deletionDate: null
    },
    pretest_exam_40: {
        courseId: seed_courses.course_17.id,
        title: 'OBS',
        subtitle: 'Kezdés',
        description: '',
        orderIndex: 0,
        moduleId: null,
        type: 'pretest',
        retakeLimit: null,
        thumbnailUrl: null,
        deletionDate: null
    },
    pretest_exam_41: {
        courseId: seed_courses.course_22.id,
        title: 'PowerPoint',
        subtitle: 'Kezdés',
        description: '',
        orderIndex: 0,
        moduleId: null,
        type: 'pretest',
        retakeLimit: null,
        thumbnailUrl: null,
        deletionDate: null
    },
    pretest_exam_42: {
        courseId: 29,
        title: 'Pretest exam course 29',
        subtitle: 'Pretest exam course 29 desc',
        description: '',
        orderIndex: 0,
        moduleId: null,
        type: 'pretest',
        retakeLimit: null,
        thumbnailUrl: null,
        deletionDate: null
    },
    pretest_exam_43: {
        courseId: seed_courses.course_27.id,
        title: 'Microsoft Excel szintfelmérő vizsga',
        subtitle: 'Most kiderítjük, hogy megy neked az Excel, majd ez alapján személyre szabjuk számodra a kurzust.',
        description: '',
        orderIndex: 0,
        moduleId: null,
        type: 'pretest',
        retakeLimit: null,
        thumbnailUrl: null,
        deletionDate: null
    }
});

export type ExamSeedDataType = ReturnType<typeof getExamSeedData>;