version: '3.3'

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'epistogram'
      POSTGRES_USER: 'dev_service_user'
      POSTGRES_DB: 'localhostDB'
    volumes: 
      - ./init:/init
      - ./init/init-script.sh:/docker-entrypoint-initdb.d/init-database.sh
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_service_user -d localhostDB"]
      interval: 20s
      timeout: 5s
      retries: 5

  server: 
    depends_on: 
      database: 
        condition: service_healthy
    restart: always
    environment:
      PGPASSWORD: 'epistogram'
      IS_DOCKERIZED: 'true'
      BRANCH_NAME: 'epitest'
    expose: 
      - 5000
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/misc/healthcheck || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    build: 
      context: ../
      dockerfile: ./config/backend.Dockerfile
      
  tests: 
    depends_on: 
      server:
        condition: service_healthy
    environment:
      IS_DOCKERIZED: 'true'
    volumes: 
      - ./out:/app/packages/server-tests/logs
    build: 
      context: ../
      dockerfile: ./config/tests.Dockerfile