echo \# ---- CONFIG FILE --- > config.env
echo \# ---- gcp >> config.env
echo BRANCH_NAME = demo >> config.env
echo BACKEND_URL = api.demo.epistogram.com >> config.env
echo MIN_INSTANCE_COUNT = 0 >> config.env
echo IS_UNDER_MAINTENANCE = false >> config.env
echo \# ---- misc >> config.env
echo DOMAIN_TEMPLATE = https://demo.[DOMAIN] >> config.env
echo ENVIRONMENT_NAME = demo >> config.env
echo HOST_PORT = 5000 >> config.env
echo JWT_SIGN_SECRET = ${{secrets.JWT_SIGN_SECRET}} >> config.env
echo IS_HOSTED_ON_GCP = true >> config.env
echo IS_LOCALHOST = false >> config.env
echo VIDEO_COMPLETED_PERCENTAGE = 5 >> config.env
echo \# ---- fileStorage >> config.env
echo FILE_STORAGE_URL = https://storage.googleapis.com/epistogram_bucket_demo >> config.env
echo FILE_STORAGE_BUCKET_NAME = epistogram_bucket_demo >> config.env
echo \# ---- mail >> config.env
echo MAIL_TOKEN_SECRET = ${{secrets.MAIL_TOKEN_SECRET}} >> config.env
echo MAIL_HOST = smtp.sendgrid.net >> config.env
echo MAIL_SENDER_MAIL = ${{secrets.MAIL_SENDER_MAIL}} >> config.env
echo MAIL_SENDER_PASSWORD = ${{secrets.MAIL_SENDER_PASSWORD}} >> config.env
echo \# ---- database >> config.env
echo DB_NAME = epistogram_DEMO >> config.env
echo DB_HOST_ADDRESS = ${{secrets.DB_HOST_ADDRESS}} >> config.env
echo DB_PORT = ${{secrets.DB_PORT}} >> config.env
echo DB_SERVICE_USER_NAME = ${{secrets.DB_SERVICE_USER_NAME}} >> config.env
echo DB_SERVICE_USER_PASSWORD = ${{secrets.DB_SERVICE_USER_PASSWORD}} >> config.env
echo DB_IS_ORM_LOGGING_ENABLED = true >> config.env