& $PSScriptRoot/../core/db_transfer `
    -src_pass "$env:GCP_POSTGRES_USER_PASSWORD" `
    -src_host '34.118.107.79' `
    -src_port '5432' `
    -src_user 'dev_service_user' `
    -src_name 'epistogram_main' `
    -dest_pass "$env:GCP_POSTGRES_USER_PASSWORD" `
    -dest_host '34.118.107.79' `
    -dest_port '5432' `
    -dest_user 'dev_service_user' `
    -dest_name 'epistogram_dev'