version: '3.8'
name: epi-test-env

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'epistogram'
      POSTGRES_USER: 'dev_service_user'
      POSTGRES_DB: 'localhostDB'
    expose:
      - 5432:7014

  test: 
    depends_on: 
      - db
    restart: always
    stdin_open: true
    environment:
      PGPASSWORD: 'epistogram'
    build: 
      context: ../
      dockerfile: ./config/test.Dockerfile

  # backend:
  #   build: 
  #     context: ../
  #     dockerfile: ./config/backend.Dockerfile