@echo off

SET /p PASSWORD=Pass: 
SET SRC_HOST=34.118.107.79
SET SRC_PORT=5432
SET SRC_DATABASE=epistogram_DEV
SET DEST_HOST=localhost
SET DEST_PORT=7014
SET DEST_DATABASE=localhostDB

call pgtransfer.bat %PASSWORD% %SRC_HOST% %SRC_PORT% %SRC_DATABASE% %DEST_HOST% %DEST_PORT% %DEST_DATABASE%