@echo off

SET /p PASSWORD=Pass: 
SET SRC_HOST=localhost
SET SRC_PORT=7014
SET SRC_DATABASE=localhostDB
SET DEST_HOST=34.118.107.79
SET DEST_PORT=5432
SET DEST_DATABASE=epistogram_DEV

call pgtransfer.bat %PASSWORD% %SRC_HOST% %SRC_PORT% %SRC_DATABASE% %DEST_HOST% %DEST_PORT% %DEST_DATABASE%