./db_transfer `
    -src_pass "$env:PGPASSWORD" `
    -src_host '34.118.107.79' `
    -src_port '5432' `
    -src_user 'dev_service_user' `
    -src_name 'epistogram_dev' `
    -dest_pass "$env:PGPASSWORD" `
    -dest_host 'localhost' `
    -dest_port '5432' `
    -dest_user 'dev_service_user' `
    -dest_name 'localhostDB'