import { AuthenticationController } from '../api/AuthenticationController';
import { CoinTransactionsController } from './../api/CoinTransactionsController';
import { CommentController } from './../api/CommentController';
import { CompanyController } from './../api/CompanyController';
import { CourseController } from './../api/CourseController';
import { CourseItemController } from './../api/CourseItemController';
import { CourseRatingController } from './../api/CourseRatingController';
import { DailyTipController } from './../api/DailyTipController';
import { EventController } from './../api/EventController';
import { ExamController } from './../api/ExamController';
import { FileController } from './../api/FileController';
import { MiscController } from './../api/MiscController';
import { ModuleController } from './../api/ModuleController';
import { PasswordChangeController } from './../api/PasswordChangeController';
import { PermissionController } from './../api/PermissionController';
import { PersonalityAssessmentController } from './../api/PersonalityAssessmentController';
import { PlaybackController } from './../api/PlaybackController';
import { PlayerController } from './../api/PlayerController';
import { PrequizController } from './../api/PrequizController';
import { PretestController } from './../api/PretestController';
import { QuestionController } from './../api/QuestionController';
import { RegistrationController } from './../api/RegistrationController';
import { RoleController } from './../api/RoleController';
import { ShopController } from './../api/ShopController';
import { SignupController } from './../api/SignupController';
import { TeacherInfoController } from './../api/TeacherInfoController';
import { TempomatController } from './../api/TempomatController';
import { UserController } from './../api/UserController';
import { UserProgressController } from './../api/UserProgressController';
import { UserStatsController } from './../api/UserStatsController';
import { VideoController } from './../api/VideoController';
import { VideoRatingController } from './../api/VideoRatingController';
import { ServiceProvider } from './servicesDI';

export const instatiateControllers = (serviceProvider: ServiceProvider) => {

    const controllers = {} as any;

    controllers.permissionController = new PermissionController(serviceProvider);
    controllers.userStatsController = new UserStatsController(serviceProvider);
    controllers.prequizController = new PrequizController(serviceProvider);
    controllers.pretestController = new PretestController(serviceProvider);
    controllers.courseRatingController = new CourseRatingController(serviceProvider);
    controllers.eventController = new EventController(serviceProvider);
    controllers.coinTransactionsController = new CoinTransactionsController(serviceProvider);
    controllers.registrationController = new RegistrationController(serviceProvider);
    controllers.miscController = new MiscController(serviceProvider);
    controllers.authenticationController = new AuthenticationController(serviceProvider);
    controllers.userController = new UserController(serviceProvider);
    controllers.fileController = new FileController(serviceProvider);
    controllers.signupController = new SignupController(serviceProvider);
    controllers.playerController = new PlayerController(serviceProvider);
    controllers.courseController = new CourseController(serviceProvider);
    controllers.moduleController = new ModuleController(serviceProvider);
    controllers.videoController = new VideoController(serviceProvider);
    controllers.questionController = new QuestionController(serviceProvider);
    controllers.examController = new ExamController(serviceProvider);
    controllers.shopController = new ShopController(serviceProvider);
    controllers.teacherInfoController = new TeacherInfoController(serviceProvider);
    controllers.passwordChangeController = new PasswordChangeController(serviceProvider);
    controllers.videoRatingController = new VideoRatingController(serviceProvider);
    controllers.personalityAssessmentController = new PersonalityAssessmentController(serviceProvider);
    controllers.dailyTipController = new DailyTipController(serviceProvider);
    controllers.userProgressController = new UserProgressController(serviceProvider);
    controllers.playbackController = new PlaybackController(serviceProvider);
    controllers.tempomatController = new TempomatController(serviceProvider);
    controllers.companyController = new CompanyController(serviceProvider);
    controllers.roleController = new RoleController(serviceProvider);
    controllers.commentController = new CommentController(serviceProvider);
    controllers.coruseItemController = new CourseItemController(serviceProvider);

    return controllers;
};