name: ci_cd_pipeline_dev
on:
  push:
    branches: [ main, demo, dev, dev2 ]
env:
  FRONTEND_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/epistogram-frontend-dev:latest
  FRONTEND_CLOUD_RUN_SVC_NAME: epistogram-frontend-dev

  BACKEND_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/epistogram-backend-dev
  BACKEND_CLOUD_RUN_SVC_NAME: epistogram-backend-dev
  
  MIGEN_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/epistogram-migen-dev
  
  CLOUD_SQL_CONNCETION_NAME: gifted-country-324010:europe-central2:epistogram
  GCP_PROJECT_NAME: gifted-country-324010

jobs:

# 
# ------ prerequisites
# 

  step1: 
    name: Hello
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: asd
        run: |
          cat ./Readme.md
          echo ${{ github.ref }}
      