name: node_docker CI

on:
  push:
    branches: [ docker_spike ]
  pull_request:
    branches: [ docker_spike ]

jobs:

  checkout_build_deploy_and_start:
    name: CI/CD job for the whole Epistogram applicaiton.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      BRANCH_NAME: docker_spike
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}-docker-spike #epistogram-backend
      CLOUD_SQL_CONNCETION_NAME: gifted-country-324010:europe-central2:epistogram 
    
    steps:

      - name: Echo pipeline branch name
        run: echo ${{ env.BRANCH_NAME }}

      - name: Echo image name
        run: echo $IMAGE_NAME

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }} # references the target branch
          path: ${{ env.BRANCH_NAME }}_repository # sets a relative folder to checkout to
        
      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
    
      - name: Build backend container
        run: |
          docker build -t $IMAGE_NAME .
        working-directory: ./${{ env.BRANCH_NAME }}_repository/epistogram_backend

      - name: Configure GCP Docker
        run: gcloud auth configure-docker --quiet

      - name: Push Docker image to GCP Container Registry
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image to GCP CloudRun
        run: |
          gcloud run deploy epistogram-backend-docker-spike \
          --image $IMAGE_NAME \
          --add-cloudsql-instances $CLOUD_SQL_CONNCETION_NAME \
          --region europe-west1 \
          --platform managed \
          --max-instances 1 \
          --port 5000 \
          --allow-unauthenticated

  