# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: node_dev CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Deploy and build 'dev'
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout 'dev' branch
      uses: actions/checkout@v2
      with:
        ref: dev # references the 'dev' branch
        path: dev_build # sets a relative folder to checkout to

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      #   cache: 'npm'
      # working-directory: ./dev_build/epistogram_backend
  
    # BUILD BACKEND
    - name: Installing dependencies for backend
      run: npm install
      working-directory: ./dev_build/epistogram_backend
      
    - name: Building backend
      run: npm run build --if-present
      working-directory: ./dev_build/epistogram_backend
      
    # BUILD FRONTEND
    # - name: Installing dependencies for frontend
    #   run: npm install
    #   working-directory: ./dev_build/epistogram_frontend
      
    # - name: Building frontend
    #   run: CI=false npm run build --if-present
    #   working-directory: ./dev_build/epistogram_frontend

    # DEPLOY TO HOSTED LOCATION
    - name: Deploying backend to hosted location
      run: cp -r ./dist/. /var/lib/apps/epistogram_backend@development
      working-directory: ./dev_build/epistogram_backend

    # START APPLICATIONS 
    - name: Starting applications
      run: pm2 start /var/lib/apps/epistogram_backend@development/main.js --name=epistogram_backend_dev
# pm2 stop --silent epistogram_backend_dev
#         pm2 delete --silent epistogram_backend_dev