name: node_docker CI

on:
  push:
    branches: [ docker_spike ]
  pull_request:
    branches: [ docker_spike ]

jobs:

  checkout_build_deploy_and_start:
    name: CI/CD job for the whole Epistogram applicaiton.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      BRANCH_NAME: docker_spike
    
    steps:

      - name: Echo pipeline branch name
        run: echo ${{ env.BRANCH_NAME }}

      # INITIALIZE
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }} # references the target branch
          path: ${{ env.BRANCH_NAME }}_repository # sets a relative folder to checkout to
    
      # BUILD BACKEND
      - name: Build backend container
        run: |
          ls ./${{ env.BRANCH_NAME }}_repository
          docker build ./${{ env.BRANCH_NAME }}_repository/epistogram_backend -t epistogram-backend