# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: node_dev CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  checkout_build_deploy_and_start:
    name: Checkout and build 'dev'
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      REACT_APP_IS_DEPLOYED: true 
    
    steps:

      # INITIALIZE
      - name: Checkout 'dev' branch
        uses: actions/checkout@v2
        with:
          ref: dev # references the 'dev' branch
          path: dev_build # sets a relative folder to checkout to

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
    
      # BUILD BACKEND
      - name: Installing dependencies for backend
        run: yarn
        working-directory: ./dev_build/epistogram_backend
        
      - name: Building backend
        run: tsc
        working-directory: ./dev_build/epistogram_backend
        
      # BUILD FRONTEND
      - run: echo $REACT_APP_IS_DEPLOYED

      - name: Installing dependencies for frontend
        run: yarn
        working-directory: ./dev_build/epistogram_frontend
        
      - name: Building frontend
        run: CI=false npm run build --if-present
        working-directory: ./dev_build/epistogram_frontend

      # DEPLOY BACKEND
      - name: Clearing target folder
        run: |
          rm -r epistogram_backend@development
          mkdir epistogram_backend@development
        working-directory: /var/lib/apps/

      - name: Copying package.json to ./build folder
        run: cp ./package.json ./build
        working-directory: ./dev_build/epistogram_backend

      - name: Deploying 'config.dev.env' file
        run: cp ./config.dev.env ./build/config.env
        working-directory: ./dev_build/epistogram_backend

      - name: Deploying backend to hosted location
        run: cp -r ./build/. /var/lib/apps/epistogram_backend@development
        working-directory: ./dev_build/epistogram_backend

      - name: Downloading node_modules to hosting location
        run: yarn
        working-directory: /var/lib/apps/epistogram_backend@development

      # DEPLOY FRONTEND
      - name: Deploying frontend to hosted location
        run: cp -r ./build/. /var/lib/apps/epistogram@development
        working-directory: ./dev_build/epistogram_frontend

      # RUN BACKEND APPLICATION  
      - run: pm2 delete epistogram_backend_dev
        continue-on-error: true
        working-directory: /var/lib/apps/epistogram_backend@development
      
      - run: pm2 start /var/lib/apps/epistogram_backend@development/server.js --name=epistogram_backend_dev
        working-directory: /var/lib/apps/epistogram_backend@development