name: node_docker CI

on:
  push:
    branches: [ docker_spike ]
  pull_request:
    branches: [ docker_spike ]

jobs:

  checkout_build_deploy_and_start:
    name: CI/CD job for the whole Epistogram applicaiton.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      PIPELINE_ENVIRONMENT: docker
    
    steps:

      - name: Echo pipeline environment
        run: echo ${{ env.PIPELINE_ENVIRONMENT }}

      # INITIALIZE
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.PIPELINE_ENVIRONMENT }} # references the target branch
          path: ${{ env.PIPELINE_ENVIRONMENT }}_repository # sets a relative folder to checkout to
    
      # BUILD BACKEND
      - name: Build backend container
        run: |
          docker build ./${{ env.PIPELINE_ENVIRONMENT }}_repository/epistogram_backend -t epistogram-backend