# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: node_dev CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        ref: dev
  
    # BUILD BACKEND
    - name: Installing dependencies for backend
      run: npm install
      working-directory: ./epistogram_backend
      
    - name: Building backend
      run: npm run build --if-present
      working-directory: ./epistogram_backend
      
    # BUILD FRONTEND
    - name: Installing dependencies for frontend
      run: npm install
      working-directory: ./epistogram_frontend
      
    - name: Building frontend
      run: CI=false npm run build --if-present
      working-directory: ./epistogram_frontend
      
#    - run: npm test
